# Generated by Django 4.0.2 on 2022-08-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_datetime_created', models.DateTimeField(auto_now_add=True)),
                ('product_datetime_modified', models.DateTimeField(auto_now=True)),
                ('product_price', models.PositiveIntegerField(default=0)),
                ('product_existence', models.BooleanField(default=True)),
                ('product_cover', models.ImageField(default='default_product/shop_cart.jpg', upload_to='product/')),
            ],
        ),
    ]
