# Generated by Django 4.0.2 on 2022-08-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_usercomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomments',
            name='product',
        ),
    ]
