# Generated by Django 4.0.2 on 2022-08-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_usercomments_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserComments',
        ),
    ]
