# Generated by Django 4.0.2 on 2022-08-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_usercomments_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='text',
            field=models.TextField(),
        ),
    ]
