# Generated by Django 4.0.2 on 2022-08-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_usercomments_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='rate',
            field=models.CharField(choices=[('1', 'Very bad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Perfect')], max_length=10),
        ),
    ]
