# Generated by Django 4.0.2 on 2022-08-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_usercomments_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_products',
            field=models.IntegerField(default=10, verbose_name='numbers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_cover',
            field=models.ImageField(default='default_product/shop_cart.jpg', upload_to='product/', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime_created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime_modified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_existence',
            field=models.BooleanField(default=True, verbose_name='existence'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.PositiveIntegerField(default=0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='comment_datetime_created'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='comment_datetime_modified'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='comment_is_active'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='rate',
            field=models.CharField(blank=True, choices=[('5', 'perfect'), ('4', 'good'), ('3', 'normal'), ('2', 'bad'), ('1', 'Very bad')], max_length=10, verbose_name='product rate'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='text',
            field=models.TextField(verbose_name='comment_text'),
        ),
    ]
