# Generated by Django 4.0.2 on 2022-08-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_all_product_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='all_product_classification',
            field=models.CharField(choices=[('Un', 'Uncategorized'), ('CAF', 'Clothing and fashion'), ('SS', 'Supermarket Items'), ('HA', 'Home Appliances'), ('T', 'Toys'), ('B', 'Books')], default=('B', 'Books'), max_length=200),
        ),
    ]
