# Generated by Django 4.0.2 on 2022-08-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_all_product_classification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='all_product_classification',
            new_name='product_classification',
        ),
    ]
