# Generated by Django 4.0.2 on 2022-08-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_rename_all_product_classification_product_product_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_classification',
            field=models.CharField(choices=[('Uncategorized', 'UN'), ('Clothing and fashion', 'CAF'), ('Supermarket Items', 'SI'), ('Home Appliances', 'HA'), ('Toys', 'TY'), ('Books', 'BO')], default=('Books', 'BO'), max_length=200),
        ),
    ]
