# Generated by Django 4.0.2 on 2022-08-23 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0023_alter_product_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_likes',
        ),
        migrations.AddField(
            model_name='product',
            name='product_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes_on_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
