# Generated by Django 4.0.2 on 2022-09-03 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0024_remove_product_product_likes_product_product_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_classification',
            field=models.CharField(choices=[('Uncategorized', 'UN'), ('Clothing and fashion', 'CAF'), ('Supermarket Items', 'SI'), ('Home Appliances', 'HA'), ('Toys', 'TY'), ('Books', 'BO')], default=('Books', 'BO'), max_length=200, verbose_name='classification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_likes',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, related_name='likes_on_products', to=settings.AUTH_USER_MODEL, verbose_name='likes_on_product'),
        ),
    ]
