# Generated by Django 4.0.2 on 2022-09-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_product_product_classification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_likes',
        ),
    ]
