# Generated by Django 4.0.2 on 2022-09-10 12:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_remove_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='description'),
        ),
    ]
