# Generated by Django 4.0.2 on 2022-09-12 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0031_remove_usercomments_email_for_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usercomments',
            name='guest_session',
            field=models.ManyToManyField(blank=True, null=True, to='sessions.Session'),
        ),
        migrations.AddField(
            model_name='usercomments',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
