# Generated by Django 4.0.2 on 2022-09-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_usercomments_email_usercomments_guest_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomments',
            name='guest_session',
        ),
    ]
