# Generated by Django 4.0.2 on 2022-08-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customusermodel_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_avatar',
            field=models.ImageField(blank=True, upload_to='profile_avatar/'),
        ),
    ]
